cmake_minimum_required(VERSION 3.22)

math(EXPR CONFIG_VERSION "((${PROJECT_VERSION_MAJOR} << 16) | (${PROJECT_VERSION_MINOR}<< 8) | ${PROJECT_VERSION_PATCH})")
math(EXPR CONFIG_VERSION "${CONFIG_VERSION} + 0" OUTPUT_FORMAT HEXADECIMAL)

function (target_add_conf TARGET_NAME CONFIG_PATH CONFIG_START_ADDRESS CONFIG_APP_ADDRESS SCRIPT_CALC_CRC)
     add_custom_command(
        TARGET ${TARGET_NAME} POST_BUILD
        COMMAND ${CMAKE_COMMAND}
        -DTARGET_PATH=$<TARGET_FILE:${TARGET_NAME}>
        -DCONFIG_START_ADDRESS=${CONFIG_START_ADDRESS}
        -DCONFIG_APP_ADDRESS=${CONFIG_APP_ADDRESS}
        -DCONFIG_PATH=${CONFIG_PATH}
        -DCONFIG_VERSION=${CONFIG_VERSION}
        -DCONFIG_OUT_PATH=$<TARGET_FILE_DIR:${TARGET_NAME}>
        -DSCRIPT_CALC_CRC=${SCRIPT_CALC_CRC}
        -DCMAKE_OBJCOPY=${CMAKE_OBJCOPY}
        -P ${CMAKE_SOURCE_DIR}/Cmake/Utils/exe_conf.cmake
        WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    )
endfunction()
